name: macOS

on: [workflow_dispatch, pull_request]

env:
  BUILD_TYPE: Debug

jobs:
  build:
    name: ${{matrix.config.os}}-${{matrix.config.cc}}-${{matrix.config.type}}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
           - { os: macos-latest, cc: clang, cxx: clang++, build-shared-libs: ON, type: shared }
           - { os: macos-latest, cc: clang, cxx: clang++, build-shared-libs: OFF, type: static }

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Install Packages
        run: |
             # Workaround homebrew bug
             brew install --overwrite python@3.12
             brew install zstd uv boost fmt sdl2

      - name: Run CMake
        working-directory: ${{github.workspace}}
        env:
          CC: ${{ matrix.config.cc }}
          CXX: ${{ matrix.config.cxx }}
          CMAKE_PREFIX_PATH: /opt/homebrew
        run: |
             mkdir build
             cd build
             cmake .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE

      - name: Build
        working-directory: ${{github.workspace}}/build
        run: MAKEFLAGS=-j$(nproc) cmake --build .
